H:
- x: 8.673617379884035e-19
  y: 0.0
  z: 1.0
- x: 1.3877787807814457e-17
  y: 0.999999977739633
  z: 0.0002109993685554854
- x: 0.0007672968277993575
  y: -0.999999325103421
  z: -0.0008723808115102827
- x: -0.9999964814858765
  y: -0.0009496333096820769
  z: 0.002476936100203792
- x: 0.0010723123610978103
  y: -0.9999993709899919
  z: -0.0003288857256067973
- x: -0.9999967796094448
  y: -0.0011395565604748192
  z: 0.0022676378867242672
P:
- x: 0.0
  y: 0.0
  z: 0.0
- x: 155.48892089708897
  y: 0.0
  z: 1.1368683772161603e-13
- x: -1.4282037989513583
  y: 0.0
  z: 614.7616185988636
- x: 640.0197211139692
  y: -0.5026410243473062
  z: 199.61075123861974
- x: 0.0
  y: 0.5026410243473062
  z: -0.037958857457397244
- x: 0.0
  y: -0.5291492212344482
  z: 0.033610452473453734
- x: 180.52102925535905
  y: 0.07476073727271193
  z: -27.539770513237727
base_markers:
- marker1_rigid2
- marker2_rigid2
- marker3_rigid2
- marker4_rigid2
- marker5_rigid2
calib_base_basemarker_pose:
  orientation:
    w: 0.5169294319653015
    x: -0.5203100278207551
    y: 0.4822277338313544
    z: 0.4790802125334256
  position:
    x: -623.2858240785945
    y: 681.3314560982808
    z: 2156.9915805633104
calib_tool_flange_pose:
  orientation:
    w: 0.5168391940072197
    x: 0.520410241844562
    y: -0.48228223345300314
    z: -0.47901385681088093
  position:
    x: 0
    y: 0
    z: 0
calibration_markers:
- marker1_rigid0
zero_config:
- 0
- 0
- 0
- 0
- 0
- 0
