H:
- x: -1.044295822397118e-20
  y: 3.306568987578852e-19
  z: 1.0
- x: -8.920520993481968e-20
  y: 0.9999999749701433
  z: -0.0002237402801179777
- x: -0.000832412407153943
  y: -0.9999995335511563
  z: 0.0004898847354533176
- x: -0.9999994087658448
  y: -0.0010427473272565926
  z: 0.0003084574075869782
- x: 3.158440334149127e-05
  y: -0.9999999994921845
  z: 4.249271192838042e-06
- x: -0.9999994349527873
  y: -0.0006744600599765649
  z: 0.0008217041643147453
P:
- x: 0.0
  y: 0.0
  z: 0.0
- x: 149.30851655120068
  y: -3.126388037344441e-13
  z: 0.0
- x: -1.1303911679325722
  y: 0.0
  z: 760.7197851892993
- x: 1082.758585687697
  y: 0.3804621294742125
  z: 199.25869530937155
- x: 0.0
  y: -0.3804621294742125
  z: 0.3877817646807671
- x: 0.0
  y: 0.4122257886506003
  z: -0.34991816726915204
- x: 219.29790896652412
  y: -9.319922649529643
  z: -33.6848016805061
base_markers:
- marker1_rigid2
- marker2_rigid2
- marker3_rigid2
- marker4_rigid2
- marker5_rigid2
calib_base_basemarker_pose:
  orientation:
    w: -0.48953488109692483
    x: 0.49093446112517763
    y: 0.5112923188200611
    z: 0.5078573813431839
  position:
    x: -152.53967570082966
    y: 589.603192531574
    z: -514.1948421287934
calib_tool_flange_pose:
  orientation:
    w: 0.4895737842339726
    x: 0.49084979602415646
    y: 0.5113212255505186
    z: 0.5078726137875397
  position:
    x: 0
    y: 0
    z: 0
calibration_markers:
- marker1_rigid0
zero_config:
- -2.0963204280432496e-06
- 2.666590057763375e-07
- -1.1248568283010094e-06
- 0.0
- -2.1194931561446783e-06
- 1.2356150441103174e-06
