device_info:
  device:
    name: motoman_robot
  manufacturer:
    name: YASKAWA
    uuid: 3561e825-f4b7-46ff-881d-3190a688f0c1
  model:
    name: D500B
    uuid: 3561e825-f4b7-46ff-881d-3190a688f0c2
  user_description: MOTOMAN Robot
  serial_number: 123456789
  device_classes:
    - class_identifier:
        name: robot
        uuid: 3561e825-f4b7-46ff-881d-3190a688f0c3
      subclasses: 
        - serial
        - serial_two_axis        
  implemented_types:
    - com.robotraconteur.robotics.robot.Robot
robot_type: serial
robot_capabilities:
- jog_command
- trajectory_command
- position_command
chains:
- kin_chain_identifier: robot_arm
  H:
  - x: 0.0
    y: -1.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: -1.0
  P:
  - x: 0.0
    y: 0.0
    z: 380
  - x: 0.0
    y: 0.0
    z: 150
  - x: 0.0
    y: 0.0
    z: 0.0

  flange_identifier: tool0
  flange_pose:
    orientation:
      w: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    position:
      x: 0.0
      y: 0.0
      z: 0.0
  joint_numbers:
  - 0
  - 1

joint_info:
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_1
  joint_limits:
    effort: 1000.0
    lower: -1.65806
    upper: 1.65806
    velocity: 1.4
    acceleration: 10
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_2
  joint_limits:
    effort: 1000.0
    lower: -1267.7527144
    upper: 1267.7527144
    velocity: 2.8
    acceleration: 15
  joint_type: revolute
  passive: false
