device_info:
  device:
    name: motoman_robot
  manufacturer:
    name: YASKAWA
    uuid: 2561e825-f4b7-46ff-881d-3190a688f0c1
  model:
    name: MA1440_A0
    uuid: 2561e825-f4b7-46ff-881d-3190a688f0c2
  user_description: MOTOMAN Robot
  serial_number: 123456789
  device_classes:
    - class_identifier:
        name: robot
        uuid: 2561e825-f4b7-46ff-881d-3190a688f0c3
      subclasses: 
        - serial
        - serial_six_axis        
  implemented_types:
    - com.robotraconteur.robotics.robot.Robot
robot_type: serial
robot_capabilities:
- jog_command
- trajectory_command
- position_command
chains:
- kin_chain_identifier: robot_arm
  H:
  - x: 0.0
    y: 0.0
    z: 1.0
  - x: 0.0
    y: 1.0
    z: 0.0
  - x: 0.0
    y: -1.0
    z: 0.0
  - x: -1.0
    y: 0.0
    z: 0.0
  - x: 0.0
    y: -1.0
    z: 0.0
  - x: -1.0
    y: 0.0
    z: 0.0
  P:
  - x: 0.0
    y: 0.0
    z: 0.0
  - x: 155
    y: 0.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 614
  - x: 640
    y: 0.0
    z: 200
  - x: 0.0
    y: 0.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 0.0
  - x: 100
    y: 0.0
    z: 0.0
  flange_identifier: tool0
  flange_pose:
    orientation:
      w: 0.0
      x: 0.7071067811865475
      y: 0.0
      z: 0.7071067811865476
    position:
      x: 0.0
      y: 0.0
      z: 0.0
  joint_numbers:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5  
joint_info:
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_1
  joint_limits:
    effort: 1000.0
    lower: -2.96705973
    upper: 2.96705973
    velocity: 4.01425728
    acceleration: 10
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_2
  joint_limits:
    effort: 1000.0
    lower: -1.57079633
    upper: 2.70526034
    velocity: 3.4906585
    acceleration: 15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_3
  joint_limits:
    effort: 1000.0
    lower: -1.48353
    upper: 2.61799
    velocity: 4.01425728
    acceleration: 15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_4
  joint_limits:
    effort: 1000.0
    lower: -2.61799388
    upper: 2.61799388
    velocity: 7.50491578
    acceleration: 20
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_5
  joint_limits:
    effort: 1000.0
    lower: -2.35619449
    upper: 1.57079633
    velocity: 7.50491578
    acceleration: 20
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_6
  joint_limits:
    effort: 1000.0
    lower: -3.66519143
    upper: 3.66519143
    velocity: 10.99557429
    acceleration: 20
  joint_type: revolute
  passive: false