calib_tool_toolmarker_pose:
  orientation:
    w: 0.015844997886208526
    x: 0.0005189492933276282
    y: 0.999869569744825
    z: -0.0030838663906880893
  position:
    x: -60.348009906026064
    y: 13.270725726733572
    z: -109.43492684487627
calib_toolmarker_flange_pose:
  orientation:
    w: -0.013384728608340129
    x: 0.7073815054425573
    y: 0.7066476006862062
    z: 0.009023482827071098
  position:
    x: 19.32497963315006
    y: 3.29804049282723
    z: 134.61614867664656
tool_markers:
  marker1_rigid5:
  - 0.4901
  - 57.16768182
  - 110.21443096
  marker2_rigid5:
  - -93.1331
  - -122.87401578
  - 57.06287791
  marker3_rigid5:
  - 93.1331
  - -122.87401578
  - 57.06287791
  marker4_rigid5:
  - 0
  - -145.06244445
  - 153.11417306
  marker5_rigid5:
  - 0
  - -145.06244445
  - 153.11417306
