H:
- x: 1.734723475976807e-18
  y: -1.734723475976807e-18
  z: 1.0
- x: 5.551115123125783e-17
  y: 0.9999825213285702
  z: -0.005912447661974463
- x: -0.010838295514402827
  y: -0.9999312604075274
  z: -0.004472785503000923
- x: -0.999790683055712
  y: 0.020413639492025546
  z: 0.0013687211851961967
- x: -0.019960622708095482
  y: -0.999788635048907
  z: -0.004925319090968047
- x: -0.9997279277311825
  y: 0.023325307637020606
  z: 2.3193829857131807e-05
P:
- x: 0.0
  y: 0.0
  z: 0.0
- x: 148.65823078044582
  y: -1.7763568394002505e-14
  z: -8.526512829121202e-14
- x: -0.798788261415773
  y: -0.2804669142341203
  z: 607.5276645728155
- x: 650.6655256829514
  y: -14.193116259432188
  z: 202.63190987609693
- x: -0.0008214222109028924
  y: 0.0032079810717935034
  z: -0.6478579071263955
- x: 0.023494441804730516
  y: 1.1765811857206996
  z: 0.6377670735693356
- x: 99.97279277311826
  y: -2.33253076370206
  z: -0.002319382985717178
base_markers:
- marker8_rigid2
calib_base_basemarker_pose:
  orientation:
    w: 0.66019551385648
    x: -0.6668470171863263
    y: 0.24786973263970627
    z: 0.24086829346055133
  position:
    x: -588.0068703849483
    y: 255.87674136480666
    z: 477.428232553409
calibration_markers:
- marker8_rigid2
- marker9_rigid2
- marker10_rigid2
- marker11_rigid2
- marker12_rigid2
- marker13_rigid2
- marker14_rigid2
- marker15_rigid2
