calib_tool_toolmarker_pose:
  orientation:
    w: 0.6976415150717906
    x: 0.14056193477692006
    y: 0.12044007461190602
    z: -0.692121988790693
  position:
    x: -1.098953910391728
    y: -12.106111971024994
    z: 349.2490776957291
tool_markers:
  marker1_rigid3:
  - 56.10951248
  - 39.3455
  - -463.4844584
  marker2_rigid3:
  - 98.25084147
  - 68.5
  - -253.47603479
  marker3_rigid3:
  - 98.25084147
  - -68.5
  - -253.47603479
  marker4_rigid3:
  - 181.2975596
  - -7.8978
  - -247.65653292
  marker5_rigid3:
  - 181.2975596
  - -7.8978
  - -247.65653292
